### ISSUE TITLE
RSA and ECC Attestation key signature scheme

### ISSUE THREAD

**Issue by Roger886** [strongswan/strongswan-docs#19]
Hi,

According to strongswan TPM2.0 guide bellow, 
_https://docs.strongswan.org/docs/5.9/tpm/tpm2.html#_rsa_endorsement_key
https://github.com/strongswan/strongswan-docs/blob/master/docs/modules/ROOT/pages/tpm/tpm2.adoc_

RSA key creation not need to specify the signature scheme but ECC key need to explicitly set：
_tpm2_createek -G rsa -c 0x81010002
tpm2_createek -G ecc -c 0x81010002_

strongswan implementation would need key signing scheme explicit set (_RSASSA_PKCS1v1_5, RSASSA_PSS_), if it not set, strongswan will abort IKE connection setup, why guide here left it open?

**Comment by tobiasbrunner** [comment]
You wouldn't use an Endorsement Key (EK) and certificate for IKE, that's what Attestation Keys (AK) and certificates are for. And when creating the latter, the guide also specifies the scheme for both key types.

**Comment by strongX509** [comment]
The **`tpm2_createek`**  command creates an  RSA or ECDSA Endorsement Key which is an encryption key. Therefore no signature scheme can be set:
````
$ pki --print --type priv --keyid 0x81010001
TPM 2.0 via TSS2 v2 available
encryption algorithm is AES-CFB with 128 bits
  privkey:   RSA 2048 bits
  keyid:     ee:c7:bf:5a:de:0f:11:84:2c:86:2b:69:84:ba:65:b9:81:d2:a9:45
  subjkey:   df:f2:e9:e7:79:98:f0:d2:0b:62:db:c0:5c:2c:eb:45:73:85:e9:79
````
````
$ pki --print --type priv --keyid 0x81010002
TPM 2.0 via TSS2 v2 available
encryption algorithm is AES-CFB with 128 bits
  privkey:   ECDSA 256 bits
  keyid:     25:db:73:13:0f:c9:c8:91:68:30:8e:02:89:c1:0d:65:bd:ad:69:2a
  subjkey:   9c:b9:fb:b0:32:81:24:82:a7:07:b2:bd:bd:d3:7c:2b:22:7f:74:bf
````
The **`tpm2_createak`**  command creates an  RSA or ECDSA Attestation Key which  is  signature key. Thus a signature scheme can be set:
````
$ tpm2_createak -C 0x81010001 -G rsa -g sha256 -s rsassa ...

$ pki --print --type priv --keyid 0x81010003
TPM 2.0 via TSS2 v2 available
signature algorithm is RSASSA with SHA256 hash
  privkey:   RSA 2048 bits
  keyid:     df:b7:8f:95:61:8f:70:84:f4:03:e8:7e:83:a6:dd:5f:c5:ff:72:b5
  subjkey:   48:82:62:15:74:a2:10:c5:75:70:c2:d6:7d:59:9f:22:d9:4f:9c:07
````
````
tpm2_createak -C 0x81010002 -G ecc -g sha256 -s ecdsa ...

$ pki --print --type priv --keyid 0x81010004
TPM 2.0 via TSS2 v2 available
signature algorithm is ECDSA with SHA256 hash
  privkey:   ECDSA 256 bits
  keyid:     ba:64:37:a4:0e:c8:42:67:8c:55:5a:f9:1b:2a:eb:ff:5f:40:c3:e3
  subjkey:   cc:83:49:87:2b:9e:f3:cb:b8:35:12:02:87:ff:14:89:28:44:a6:04

````
