### ISSUE TITLE
Android incompatibility caused by openssl-pkcs12 changes.

### ISSUE THREAD

**Issue by yjiang-yh135** [strongswan/strongswan-docs#5]
Since Openssl 3, the default ciphers for pkcs12 have changed and the openssl-pkcs12 command in the certificates quickstart section no longer work for android (tested on android 12, where you get a misleading "incorrect password" error when importing into the certificate store). You have to add the `-legacy` flag to revert back to the old ciphers as a workaround.

Default openssl 3 settings work fine on windows 10 though (most likely on win 11 too).

**Comment by tobiasbrunner** [comment]
Thanks. We already had a note about that option on the page on [profiles for Apple clients](https://docs.strongswan.org/docs/5.9/interop/appleIkev2Profile.html#_known_issues). I've now added a similar note to [certificates quickstart page](https://docs.strongswan.org/docs/5.9/pki/pkiQuickstart.html#_pkcs12_container) that also mentions Android clients.
