### ISSUE TITLE
Fedora URL no longer works

### ISSUE THREAD

**Issue by RobertCElliott** [strongswan/strongswan-docs#6]
On https://docs.strongswan.org/docs/5.9/install/install.html, the link to Fedora at
https://apps.fedoraproject.org/packages/strongswan/overview/
should be
https://packages.fedoraproject.org/pkgs/strongswan/strongswan/

**Comment by strongX509** [comment]
Thanks a lot!
Tthe link to Fedora has been fixed by [fae72421057f34ae176030831c468530bfb21d5b](https://github.com/strongswan/strongswan-docs/commit/fae72421057f34ae176030831c468530bfb21d5b).
